### ISSUE TITLE
Format of depth image

### ISSUE THREAD

**Issue by exnx** [felixchenfy/ros_detect_planes_from_depth_img#2]
Hi, I'm a little new to working with depth data.  I have an image coming the Realsense D435 camera, and saved it as an inverse colorization png.  But that doesn't seem to work (not 2 channels).  Do you have tips on how to get it in the right format?  Thanks so much!

Eric

**Comment by felixchenfy** [comment]
What library are you using to read the image data?
If you are using ROS, you are probably using this library:
https://github.com/IntelRealSense/realsense-ros The images read by the
library will be published to ROS topics. For more details, please see that
github.
If you are using other libraries, please search on google for their
documentation, or search for how other people use the library.

In general, the D435 camera should return two types of image: RGB image (3
channels), and depth image (1 channel).

**Comment by exnx** [comment]
Oh ok, I am using the realsense library directly into my Python script, and processing with OpenCV.  

I'm curious how you save your depth data?  As a grayscale?  Is there a way to save it in opencv format?  I tried taking the raw depth output from realsense:
        frames = pipeline.wait_for_frames()
        depth_frame = frames.get_depth_frame()

and then converting to a numpy array.  I then normalized to be between 0-255, and dtype=np.uint8, but that doesn't let me save the image in that format.  Would love to see how you saved it?

Thanks again!

Eric

**Comment by felixchenfy** [comment]
Hi, looks like you are able to read the image from the camera.
Try displaying that depth_frame first, and then save it.
I can't help with this low level debug. Sorry about that.

"Would love to see how you saved it?" --- Convert the data to the **right
format** (np.uint8 or np.uint16), and then call cv2.imwrite. I think you
are stuck at this "right format" step, which I can't help with you to debug

**Comment by exnx** [comment]
great got it to work on a single image!  Looks good!
